#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPS19_BattlePassRewardGrid

#include "Basic.hpp"

#include "BPS19_BattlePassRewardGrid_classes.hpp"
#include "BPS19_BattlePassRewardGrid_parameters.hpp"


namespace SDK
{

// Function BPS19_BattlePassRewardGrid.BPS19_BattlePassRewardGrid_C.ExecuteUbergraph_BPS19_BattlePassRewardGrid
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPS19_BattlePassRewardGrid_C::ExecuteUbergraph_BPS19_BattlePassRewardGrid(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_BPS19_BattlePassRewardGrid");

	Params::BPS19_BattlePassRewardGrid_C_ExecuteUbergraph_BPS19_BattlePassRewardGrid Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPS19_BattlePassRewardGrid.BPS19_BattlePassRewardGrid_C.OnPageSelected
// (Event, Public, BlueprintEvent)

void UBPS19_BattlePassRewardGrid_C::OnPageSelected()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnPageSelected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPS19_BattlePassRewardGrid.BPS19_BattlePassRewardGrid_C.OnPageUnselected
// (Event, Public, BlueprintEvent)

void UBPS19_BattlePassRewardGrid_C::OnPageUnselected()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnPageUnselected");

	UObject::ProcessEvent(Func, nullptr);
}

}

