#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPS19_BattlePassRewardGrid

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BattlePassBase_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPS19_BattlePassRewardGrid.BPS19_BattlePassRewardGrid_C
// 0x0008 (0x0400 - 0x03F8)
class UBPS19_BattlePassRewardGrid_C final : public UFortBattlePassRewardGrid
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03F8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BPS19_BattlePassRewardGrid(int32 EntryPoint);
	void OnPageSelected();
	void OnPageUnselected();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPS19_BattlePassRewardGrid_C">();
	}
	static class UBPS19_BattlePassRewardGrid_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPS19_BattlePassRewardGrid_C>();
	}
};
static_assert(alignof(UBPS19_BattlePassRewardGrid_C) == 0x000008, "Wrong alignment on UBPS19_BattlePassRewardGrid_C");
static_assert(sizeof(UBPS19_BattlePassRewardGrid_C) == 0x000400, "Wrong size on UBPS19_BattlePassRewardGrid_C");
static_assert(offsetof(UBPS19_BattlePassRewardGrid_C, UberGraphFrame) == 0x0003F8, "Member 'UBPS19_BattlePassRewardGrid_C::UberGraphFrame' has a wrong offset!");

}

