#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyle_TextOnlyBase_EmptyFocus

#include "Basic.hpp"

#include "ButtonStyle_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-TextOnlyBase_EmptyFocus.ButtonStyle-TextOnlyBase_EmptyFocus_C
// 0x0000 (0x06B0 - 0x06B0)
class UButtonStyle_TextOnlyBase_EmptyFocus_C final : public UButtonStyle_Base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-TextOnlyBase_EmptyFocus_C">();
	}
	static class UButtonStyle_TextOnlyBase_EmptyFocus_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyle_TextOnlyBase_EmptyFocus_C>();
	}
};
static_assert(alignof(UButtonStyle_TextOnlyBase_EmptyFocus_C) == 0x000010, "Wrong alignment on UButtonStyle_TextOnlyBase_EmptyFocus_C");
static_assert(sizeof(UButtonStyle_TextOnlyBase_EmptyFocus_C) == 0x0006B0, "Wrong size on UButtonStyle_TextOnlyBase_EmptyFocus_C");

}

