#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DiscoveryBrowserUI

#include "Basic.hpp"


namespace SDK
{

// Enum DiscoveryBrowserUI.EFortActivityBrowserTagType
// NumValues: 0x0005
enum class EFortActivityBrowserTagType : uint8
{
	Default                                  = 0,
	EpicOriginal                             = 1,
	SquadSize                                = 2,
	MaxPlayers                               = 3,
	XP                                       = 4,
};

// ScriptStruct DiscoveryBrowserUI.FortActivityScaleFontData
// 0x0008 (0x0008 - 0x0000)
struct FFortActivityScaleFontData final
{
public:
	int32                                         CharacterCountStart;                               // 0x0000(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         FontSize;                                          // 0x0004(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FFortActivityScaleFontData) == 0x000004, "Wrong alignment on FFortActivityScaleFontData");
static_assert(sizeof(FFortActivityScaleFontData) == 0x000008, "Wrong size on FFortActivityScaleFontData");
static_assert(offsetof(FFortActivityScaleFontData, CharacterCountStart) == 0x000000, "Member 'FFortActivityScaleFontData::CharacterCountStart' has a wrong offset!");
static_assert(offsetof(FFortActivityScaleFontData, FontSize) == 0x000004, "Member 'FFortActivityScaleFontData::FontSize' has a wrong offset!");

}

