#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FuelIndicator

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FuelIndicator.FuelIndicator_C
// 0x0010 (0x08D0 - 0x08C0)
class AFuelIndicator_C final : public ABuildingGameplayActor
{
public:
	class UAthenaSpecialActorComponent*           AthenaSpecialActor;                                // 0x08C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x08C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FuelIndicator_C">();
	}
	static class AFuelIndicator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFuelIndicator_C>();
	}
};
static_assert(alignof(AFuelIndicator_C) == 0x000008, "Wrong alignment on AFuelIndicator_C");
static_assert(sizeof(AFuelIndicator_C) == 0x0008D0, "Wrong size on AFuelIndicator_C");
static_assert(offsetof(AFuelIndicator_C, AthenaSpecialActor) == 0x0008C0, "Member 'AFuelIndicator_C::AthenaSpecialActor' has a wrong offset!");
static_assert(offsetof(AFuelIndicator_C, DefaultSceneRoot) == 0x0008C8, "Member 'AFuelIndicator_C::DefaultSceneRoot' has a wrong offset!");

}

