#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Galileo_Lobster_StaggerMeleeHit

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Galileo_Lobster_StaggerMeleeHit.GA_Galileo_Lobster_StaggerMeleeHit_C
// 0x0008 (0x0AB0 - 0x0AA8)
class UGA_Galileo_Lobster_StaggerMeleeHit_C final : public UFortGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0AA8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void Cancelled_C74ABBE842C11F9B9741D5BF7D4C4CE6(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag);
	void Completed_C74ABBE842C11F9B9741D5BF7D4C4CE6(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag);
	void ExecuteUbergraph_GA_Galileo_Lobster_StaggerMeleeHit(int32 EntryPoint);
	void K2_ActivateAbility();
	void Triggered_C74ABBE842C11F9B9741D5BF7D4C4CE6(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Galileo_Lobster_StaggerMeleeHit_C">();
	}
	static class UGA_Galileo_Lobster_StaggerMeleeHit_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Galileo_Lobster_StaggerMeleeHit_C>();
	}
};
static_assert(alignof(UGA_Galileo_Lobster_StaggerMeleeHit_C) == 0x000008, "Wrong alignment on UGA_Galileo_Lobster_StaggerMeleeHit_C");
static_assert(sizeof(UGA_Galileo_Lobster_StaggerMeleeHit_C) == 0x000AB0, "Wrong size on UGA_Galileo_Lobster_StaggerMeleeHit_C");
static_assert(offsetof(UGA_Galileo_Lobster_StaggerMeleeHit_C, UberGraphFrame) == 0x000AA8, "Member 'UGA_Galileo_Lobster_StaggerMeleeHit_C::UberGraphFrame' has a wrong offset!");

}

