#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MinigameStat_Time

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MinigameStat_Time.MinigameStat_Time_C
// 0x0000 (0x0190 - 0x0190)
class UMinigameStat_Time_C : public UFortMinigameStatFilter
{
public:
	int32 Accumulate(int32 A, int32 B) const;
	int32 Compare(int32 FirstScore, int32 SecondScore) const;
	class FText FormatStat(int32 InCount) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MinigameStat_Time_C">();
	}
	static class UMinigameStat_Time_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMinigameStat_Time_C>();
	}
};
static_assert(alignof(UMinigameStat_Time_C) == 0x000008, "Wrong alignment on UMinigameStat_Time_C");
static_assert(sizeof(UMinigameStat_Time_C) == 0x000190, "Wrong size on UMinigameStat_Time_C");

}

