#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ShowdownEventTile

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "FortniteUI_structs.hpp"


namespace SDK::Params
{

// Function ShowdownEventTile.ShowdownEventTile_C.EventColorize
// 0x01D0 (0x01D0 - 0x0000)
struct ShowdownEventTile_C_EventColorize final
{
public:
	struct FFortTournamentDisplayInfo             DisplayInfo;                                       // 0x0000(0x01D0)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(ShowdownEventTile_C_EventColorize) == 0x000008, "Wrong alignment on ShowdownEventTile_C_EventColorize");
static_assert(sizeof(ShowdownEventTile_C_EventColorize) == 0x0001D0, "Wrong size on ShowdownEventTile_C_EventColorize");
static_assert(offsetof(ShowdownEventTile_C_EventColorize, DisplayInfo) == 0x000000, "Member 'ShowdownEventTile_C_EventColorize::DisplayInfo' has a wrong offset!");

// Function ShowdownEventTile.ShowdownEventTile_C.EventColorizeDispatch
// 0x01D0 (0x01D0 - 0x0000)
struct ShowdownEventTile_C_EventColorizeDispatch final
{
public:
	struct FFortTournamentDisplayInfo             DisplayInfo;                                       // 0x0000(0x01D0)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(ShowdownEventTile_C_EventColorizeDispatch) == 0x000008, "Wrong alignment on ShowdownEventTile_C_EventColorizeDispatch");
static_assert(sizeof(ShowdownEventTile_C_EventColorizeDispatch) == 0x0001D0, "Wrong size on ShowdownEventTile_C_EventColorizeDispatch");
static_assert(offsetof(ShowdownEventTile_C_EventColorizeDispatch, DisplayInfo) == 0x000000, "Member 'ShowdownEventTile_C_EventColorizeDispatch::DisplayInfo' has a wrong offset!");

// Function ShowdownEventTile.ShowdownEventTile_C.EventIntro
// 0x0004 (0x0004 - 0x0000)
struct ShowdownEventTile_C_EventIntro final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ShowdownEventTile_C_EventIntro) == 0x000004, "Wrong alignment on ShowdownEventTile_C_EventIntro");
static_assert(sizeof(ShowdownEventTile_C_EventIntro) == 0x000004, "Wrong size on ShowdownEventTile_C_EventIntro");
static_assert(offsetof(ShowdownEventTile_C_EventIntro, Index_0) == 0x000000, "Member 'ShowdownEventTile_C_EventIntro::Index_0' has a wrong offset!");

// Function ShowdownEventTile.ShowdownEventTile_C.EventResize
// 0x0001 (0x0001 - 0x0000)
struct ShowdownEventTile_C_EventResize final
{
public:
	bool                                          Out;                                               // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ShowdownEventTile_C_EventResize) == 0x000001, "Wrong alignment on ShowdownEventTile_C_EventResize");
static_assert(sizeof(ShowdownEventTile_C_EventResize) == 0x000001, "Wrong size on ShowdownEventTile_C_EventResize");
static_assert(offsetof(ShowdownEventTile_C_EventResize, Out) == 0x000000, "Member 'ShowdownEventTile_C_EventResize::Out' has a wrong offset!");

// Function ShowdownEventTile.ShowdownEventTile_C.EventSetState
// 0x0001 (0x0001 - 0x0000)
struct ShowdownEventTile_C_EventSetState final
{
public:
	EFortShowdownEventState                       EventState;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ShowdownEventTile_C_EventSetState) == 0x000001, "Wrong alignment on ShowdownEventTile_C_EventSetState");
static_assert(sizeof(ShowdownEventTile_C_EventSetState) == 0x000001, "Wrong size on ShowdownEventTile_C_EventSetState");
static_assert(offsetof(ShowdownEventTile_C_EventSetState, EventState) == 0x000000, "Member 'ShowdownEventTile_C_EventSetState::EventState' has a wrong offset!");

// Function ShowdownEventTile.ShowdownEventTile_C.ExecuteUbergraph_ShowdownEventTile
// 0x0650 (0x0650 - 0x0000)
struct ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable;                               // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Temp_float_Variable_1;                             // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_2;                             // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_2;                              // 0x0015(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_16[0x2];                                       // 0x0016(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0018(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(const struct FFortTournamentDisplayInfo& DisplayInfo)> K2Node_CreateDelegate_OutputDelegate_1;            // 0x0028(0x0010)(ZeroConstructor, NoDestructor)
	float                                         Temp_float_Variable_3;                             // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_3;                              // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3D[0x3];                                       // 0x003D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_CustomEvent_Index;                          // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_IntFloat_ReturnValue;            // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_Out;                            // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51[0x3];                                       // 0x0051(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetEndTime_ReturnValue;                   // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_1;              // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_PauseAnimation_ReturnValue;               // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetStartTime_ReturnValue;                 // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_PauseAnimation_ReturnValue_1;             // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue;         // 0x0074(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_75[0x3];                                       // 0x0075(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetEndTime_ReturnValue_1;                 // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_2;              // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue;          // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetStartTime_ReturnValue_1;               // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_PauseAnimation_ReturnValue_2;             // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_PauseAnimation_ReturnValue_3;             // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_PauseAnimation_ReturnValue_4;             // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_PauseAnimation_ReturnValue_5;             // 0x009C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_1;       // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A1[0x3];                                       // 0x00A1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Add_FloatFloat_ReturnValue_1;             // 0x00A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_3;              // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetEndTime_ReturnValue_2;                 // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetStartTime_ReturnValue_2;               // 0x00B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_1;        // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_2;       // 0x00BC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_BD[0x3];                                       // 0x00BD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Select_Default;                             // 0x00C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C4[0x4];                                       // 0x00C4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_4;              // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue_2;             // 0x00D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetEndTime_ReturnValue_3;                 // 0x00D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_5;              // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_2;        // 0x00E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Select_Default_1;                           // 0x00E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_6;              // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFocusEvent                            K2Node_Event_InFocusEvent_1;                       // 0x00F0(0x0008)(NoDestructor)
	float                                         CallFunc_PauseAnimation_ReturnValue_6;             // 0x00F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetStartTime_ReturnValue_3;               // 0x00FC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_PauseAnimation_ReturnValue_7;             // 0x0100(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_3;       // 0x0104(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_105[0x3];                                      // 0x0105(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Add_FloatFloat_ReturnValue_3;             // 0x0108(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetEndTime_ReturnValue_4;                 // 0x010C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_7;              // 0x0110(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_3;        // 0x0118(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_PauseAnimation_ReturnValue_8;             // 0x011C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetStartTime_ReturnValue_4;               // 0x0120(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_PauseAnimation_ReturnValue_9;             // 0x0124(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_4;       // 0x0128(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_129[0x3];                                      // 0x0129(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Add_FloatFloat_ReturnValue_4;             // 0x012C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetEndTime_ReturnValue_5;                 // 0x0130(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_134[0x4];                                      // 0x0134(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_8;              // 0x0138(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_4;        // 0x0140(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFocusEvent                            K2Node_Event_InFocusEvent;                         // 0x0144(0x0008)(NoDestructor)
	EFortShowdownEventState                       K2Node_CustomEvent_EventState;                     // 0x014C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x014D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x014E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_2;        // 0x014F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0150(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_3;        // 0x0151(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_4;        // 0x0152(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_1;                  // 0x0153(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_2;                  // 0x0154(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_5;        // 0x0155(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_3;                  // 0x0156(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_157[0x1];                                      // 0x0157(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Temp_float_Variable_4;                             // 0x0158(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_5;                             // 0x015C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_PauseAnimation_ReturnValue_10;            // 0x0160(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetStartTime_ReturnValue_5;               // 0x0164(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_PauseAnimation_ReturnValue_11;            // 0x0168(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_5;       // 0x016C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_16D[0x3];                                      // 0x016D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Add_FloatFloat_ReturnValue_5;             // 0x0170(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_174[0x4];                                      // 0x0174(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_9;              // 0x0178(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetEndTime_ReturnValue_6;                 // 0x0180(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_4;                              // 0x0184(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_185[0x3];                                      // 0x0185(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_5;        // 0x0188(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Select_Default_2;                           // 0x018C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Select_Default_3;                           // 0x0190(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_194[0x4];                                      // 0x0194(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_10;             // 0x0198(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(EFortShowdownEventState EventState)> K2Node_CreateDelegate_OutputDelegate_2;            // 0x01A0(0x0010)(ZeroConstructor, NoDestructor)
	float                                         Temp_float_Variable_6;                             // 0x01B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_PauseAnimation_ReturnValue_12;            // 0x01B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetStartTime_ReturnValue_6;               // 0x01B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_PauseAnimation_ReturnValue_13;            // 0x01BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_6;       // 0x01C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C1[0x3];                                      // 0x01C1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Add_FloatFloat_ReturnValue_6;             // 0x01C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetEndTime_ReturnValue_7;                 // 0x01C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1CC[0x4];                                      // 0x01CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_11;             // 0x01D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_6;        // 0x01D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_PauseAnimation_ReturnValue_14;            // 0x01DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetStartTime_ReturnValue_7;               // 0x01E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_PauseAnimation_ReturnValue_15;            // 0x01E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_7;       // 0x01E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1E9[0x3];                                      // 0x01E9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Add_FloatFloat_ReturnValue_7;             // 0x01EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetEndTime_ReturnValue_8;                 // 0x01F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1F4[0x4];                                      // 0x01F4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_12;             // 0x01F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_7;        // 0x0200(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_5;                              // 0x0204(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_205[0x3];                                      // 0x0205(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Select_Default_4;                           // 0x0208(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_20C[0x4];                                      // 0x020C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFortTournamentDisplayInfo             K2Node_CustomEvent_DisplayInfo_1;                  // 0x0210(0x01D0)()
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_13;             // 0x03E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_7;                             // 0x03E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3EC[0x4];                                      // 0x03EC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFortTournamentDisplayInfo             K2Node_CustomEvent_DisplayInfo;                    // 0x03F0(0x01D0)()
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue;           // 0x05C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_6;                              // 0x05C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5C9[0x3];                                      // 0x05C9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Temp_float_Variable_8;                             // 0x05CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Select_Default_5;                           // 0x05D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_7;                              // 0x05D4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5D5[0x3];                                      // 0x05D5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_14;             // 0x05D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_9;                             // 0x05E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Select_Default_6;                           // 0x05E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_15;             // 0x05E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_8;                              // 0x05F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5F1[0x3];                                      // 0x05F1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Select_Default_7;                           // 0x05F4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_16;             // 0x05F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_PauseAnimation_ReturnValue_16;            // 0x0600(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetStartTime_ReturnValue_8;               // 0x0604(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_PauseAnimation_ReturnValue_17;            // 0x0608(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_8;       // 0x060C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_60D[0x3];                                      // 0x060D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Add_FloatFloat_ReturnValue_8;             // 0x0610(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_614[0x4];                                      // 0x0614(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_17;             // 0x0618(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetEndTime_ReturnValue_9;                 // 0x0620(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_10;                            // 0x0624(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_8;        // 0x0628(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Select_Default_8;                           // 0x062C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_9;                              // 0x0630(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_631[0x7];                                      // 0x0631(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_18;             // 0x0638(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Select_Default_9;                           // 0x0640(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_644[0x4];                                      // 0x0644(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_19;             // 0x0648(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile) == 0x000008, "Wrong alignment on ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile");
static_assert(sizeof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile) == 0x000650, "Wrong size on ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, EntryPoint) == 0x000000, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::EntryPoint' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, Temp_float_Variable) == 0x000004, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::Temp_float_Variable' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, Temp_bool_Variable) == 0x000008, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, Temp_float_Variable_1) == 0x00000C, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::Temp_float_Variable_1' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, Temp_float_Variable_2) == 0x000010, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::Temp_float_Variable_2' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, Temp_bool_Variable_1) == 0x000014, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, Temp_bool_Variable_2) == 0x000015, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::Temp_bool_Variable_2' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, K2Node_CreateDelegate_OutputDelegate) == 0x000018, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, K2Node_CreateDelegate_OutputDelegate_1) == 0x000028, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, Temp_float_Variable_3) == 0x000038, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::Temp_float_Variable_3' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, Temp_bool_Variable_3) == 0x00003C, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::Temp_bool_Variable_3' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, K2Node_CustomEvent_Index) == 0x000040, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::K2Node_CustomEvent_Index' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_Multiply_IntFloat_ReturnValue) == 0x000044, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_Multiply_IntFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PlayAnimation_ReturnValue) == 0x000048, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, K2Node_CustomEvent_Out) == 0x000050, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::K2Node_CustomEvent_Out' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_GetEndTime_ReturnValue) == 0x000054, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_GetEndTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_Not_PreBool_ReturnValue) == 0x000058, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PlayAnimation_ReturnValue_1) == 0x000060, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PlayAnimation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PauseAnimation_ReturnValue) == 0x000068, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PauseAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_GetStartTime_ReturnValue) == 0x00006C, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_GetStartTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PauseAnimation_ReturnValue_1) == 0x000070, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PauseAnimation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_LessEqual_FloatFloat_ReturnValue) == 0x000074, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_LessEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_Add_FloatFloat_ReturnValue) == 0x000078, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_GetEndTime_ReturnValue_1) == 0x00007C, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_GetEndTime_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PlayAnimation_ReturnValue_2) == 0x000080, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PlayAnimation_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_Subtract_FloatFloat_ReturnValue) == 0x000088, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_Subtract_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_GetStartTime_ReturnValue_1) == 0x00008C, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_GetStartTime_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PauseAnimation_ReturnValue_2) == 0x000090, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PauseAnimation_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PauseAnimation_ReturnValue_3) == 0x000094, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PauseAnimation_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PauseAnimation_ReturnValue_4) == 0x000098, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PauseAnimation_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PauseAnimation_ReturnValue_5) == 0x00009C, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PauseAnimation_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_LessEqual_FloatFloat_ReturnValue_1) == 0x0000A0, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_LessEqual_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_Add_FloatFloat_ReturnValue_1) == 0x0000A4, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_Add_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PlayAnimation_ReturnValue_3) == 0x0000A8, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PlayAnimation_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_GetEndTime_ReturnValue_2) == 0x0000B0, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_GetEndTime_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_GetStartTime_ReturnValue_2) == 0x0000B4, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_GetStartTime_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_Subtract_FloatFloat_ReturnValue_1) == 0x0000B8, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_Subtract_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_LessEqual_FloatFloat_ReturnValue_2) == 0x0000BC, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_LessEqual_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, K2Node_Select_Default) == 0x0000C0, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PlayAnimation_ReturnValue_4) == 0x0000C8, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PlayAnimation_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_Add_FloatFloat_ReturnValue_2) == 0x0000D0, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_Add_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_GetEndTime_ReturnValue_3) == 0x0000D4, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_GetEndTime_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PlayAnimation_ReturnValue_5) == 0x0000D8, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PlayAnimation_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_Subtract_FloatFloat_ReturnValue_2) == 0x0000E0, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_Subtract_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, K2Node_Select_Default_1) == 0x0000E4, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PlayAnimation_ReturnValue_6) == 0x0000E8, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PlayAnimation_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, K2Node_Event_InFocusEvent_1) == 0x0000F0, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::K2Node_Event_InFocusEvent_1' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PauseAnimation_ReturnValue_6) == 0x0000F8, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PauseAnimation_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_GetStartTime_ReturnValue_3) == 0x0000FC, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_GetStartTime_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PauseAnimation_ReturnValue_7) == 0x000100, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PauseAnimation_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_LessEqual_FloatFloat_ReturnValue_3) == 0x000104, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_LessEqual_FloatFloat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_Add_FloatFloat_ReturnValue_3) == 0x000108, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_Add_FloatFloat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_GetEndTime_ReturnValue_4) == 0x00010C, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_GetEndTime_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PlayAnimation_ReturnValue_7) == 0x000110, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PlayAnimation_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_Subtract_FloatFloat_ReturnValue_3) == 0x000118, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_Subtract_FloatFloat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PauseAnimation_ReturnValue_8) == 0x00011C, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PauseAnimation_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_GetStartTime_ReturnValue_4) == 0x000120, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_GetStartTime_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PauseAnimation_ReturnValue_9) == 0x000124, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PauseAnimation_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_LessEqual_FloatFloat_ReturnValue_4) == 0x000128, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_LessEqual_FloatFloat_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_Add_FloatFloat_ReturnValue_4) == 0x00012C, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_Add_FloatFloat_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_GetEndTime_ReturnValue_5) == 0x000130, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_GetEndTime_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PlayAnimation_ReturnValue_8) == 0x000138, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PlayAnimation_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_Subtract_FloatFloat_ReturnValue_4) == 0x000140, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_Subtract_FloatFloat_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, K2Node_Event_InFocusEvent) == 0x000144, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::K2Node_Event_InFocusEvent' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, K2Node_CustomEvent_EventState) == 0x00014C, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::K2Node_CustomEvent_EventState' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x00014D, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_EqualEqual_ByteByte_ReturnValue_1) == 0x00014E, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_EqualEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_EqualEqual_ByteByte_ReturnValue_2) == 0x00014F, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_EqualEqual_ByteByte_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_BooleanOR_ReturnValue) == 0x000150, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_EqualEqual_ByteByte_ReturnValue_3) == 0x000151, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_EqualEqual_ByteByte_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_EqualEqual_ByteByte_ReturnValue_4) == 0x000152, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_EqualEqual_ByteByte_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_BooleanOR_ReturnValue_1) == 0x000153, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_BooleanOR_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_BooleanOR_ReturnValue_2) == 0x000154, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_BooleanOR_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_EqualEqual_ByteByte_ReturnValue_5) == 0x000155, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_EqualEqual_ByteByte_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_BooleanOR_ReturnValue_3) == 0x000156, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_BooleanOR_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, Temp_float_Variable_4) == 0x000158, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::Temp_float_Variable_4' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, Temp_float_Variable_5) == 0x00015C, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::Temp_float_Variable_5' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PauseAnimation_ReturnValue_10) == 0x000160, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PauseAnimation_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_GetStartTime_ReturnValue_5) == 0x000164, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_GetStartTime_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PauseAnimation_ReturnValue_11) == 0x000168, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PauseAnimation_ReturnValue_11' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_LessEqual_FloatFloat_ReturnValue_5) == 0x00016C, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_LessEqual_FloatFloat_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_Add_FloatFloat_ReturnValue_5) == 0x000170, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_Add_FloatFloat_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PlayAnimation_ReturnValue_9) == 0x000178, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PlayAnimation_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_GetEndTime_ReturnValue_6) == 0x000180, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_GetEndTime_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, Temp_bool_Variable_4) == 0x000184, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::Temp_bool_Variable_4' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_Subtract_FloatFloat_ReturnValue_5) == 0x000188, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_Subtract_FloatFloat_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, K2Node_Select_Default_2) == 0x00018C, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::K2Node_Select_Default_2' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, K2Node_Select_Default_3) == 0x000190, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::K2Node_Select_Default_3' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PlayAnimation_ReturnValue_10) == 0x000198, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PlayAnimation_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, K2Node_CreateDelegate_OutputDelegate_2) == 0x0001A0, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, Temp_float_Variable_6) == 0x0001B0, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::Temp_float_Variable_6' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PauseAnimation_ReturnValue_12) == 0x0001B4, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PauseAnimation_ReturnValue_12' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_GetStartTime_ReturnValue_6) == 0x0001B8, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_GetStartTime_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PauseAnimation_ReturnValue_13) == 0x0001BC, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PauseAnimation_ReturnValue_13' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_LessEqual_FloatFloat_ReturnValue_6) == 0x0001C0, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_LessEqual_FloatFloat_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_Add_FloatFloat_ReturnValue_6) == 0x0001C4, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_Add_FloatFloat_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_GetEndTime_ReturnValue_7) == 0x0001C8, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_GetEndTime_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PlayAnimation_ReturnValue_11) == 0x0001D0, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PlayAnimation_ReturnValue_11' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_Subtract_FloatFloat_ReturnValue_6) == 0x0001D8, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_Subtract_FloatFloat_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PauseAnimation_ReturnValue_14) == 0x0001DC, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PauseAnimation_ReturnValue_14' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_GetStartTime_ReturnValue_7) == 0x0001E0, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_GetStartTime_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PauseAnimation_ReturnValue_15) == 0x0001E4, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PauseAnimation_ReturnValue_15' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_LessEqual_FloatFloat_ReturnValue_7) == 0x0001E8, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_LessEqual_FloatFloat_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_Add_FloatFloat_ReturnValue_7) == 0x0001EC, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_Add_FloatFloat_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_GetEndTime_ReturnValue_8) == 0x0001F0, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_GetEndTime_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PlayAnimation_ReturnValue_12) == 0x0001F8, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PlayAnimation_ReturnValue_12' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_Subtract_FloatFloat_ReturnValue_7) == 0x000200, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_Subtract_FloatFloat_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, Temp_bool_Variable_5) == 0x000204, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::Temp_bool_Variable_5' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, K2Node_Select_Default_4) == 0x000208, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::K2Node_Select_Default_4' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, K2Node_CustomEvent_DisplayInfo_1) == 0x000210, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::K2Node_CustomEvent_DisplayInfo_1' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PlayAnimation_ReturnValue_13) == 0x0003E0, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PlayAnimation_ReturnValue_13' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, Temp_float_Variable_7) == 0x0003E8, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::Temp_float_Variable_7' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, K2Node_CustomEvent_DisplayInfo) == 0x0003F0, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::K2Node_CustomEvent_DisplayInfo' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_GetDynamicMaterial_ReturnValue) == 0x0005C0, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_GetDynamicMaterial_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, Temp_bool_Variable_6) == 0x0005C8, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::Temp_bool_Variable_6' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, Temp_float_Variable_8) == 0x0005CC, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::Temp_float_Variable_8' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, K2Node_Select_Default_5) == 0x0005D0, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::K2Node_Select_Default_5' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, Temp_bool_Variable_7) == 0x0005D4, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::Temp_bool_Variable_7' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PlayAnimation_ReturnValue_14) == 0x0005D8, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PlayAnimation_ReturnValue_14' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, Temp_float_Variable_9) == 0x0005E0, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::Temp_float_Variable_9' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, K2Node_Select_Default_6) == 0x0005E4, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::K2Node_Select_Default_6' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PlayAnimation_ReturnValue_15) == 0x0005E8, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PlayAnimation_ReturnValue_15' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, Temp_bool_Variable_8) == 0x0005F0, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::Temp_bool_Variable_8' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, K2Node_Select_Default_7) == 0x0005F4, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::K2Node_Select_Default_7' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PlayAnimation_ReturnValue_16) == 0x0005F8, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PlayAnimation_ReturnValue_16' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PauseAnimation_ReturnValue_16) == 0x000600, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PauseAnimation_ReturnValue_16' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_GetStartTime_ReturnValue_8) == 0x000604, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_GetStartTime_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PauseAnimation_ReturnValue_17) == 0x000608, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PauseAnimation_ReturnValue_17' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_LessEqual_FloatFloat_ReturnValue_8) == 0x00060C, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_LessEqual_FloatFloat_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_Add_FloatFloat_ReturnValue_8) == 0x000610, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_Add_FloatFloat_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PlayAnimation_ReturnValue_17) == 0x000618, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PlayAnimation_ReturnValue_17' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_GetEndTime_ReturnValue_9) == 0x000620, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_GetEndTime_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, Temp_float_Variable_10) == 0x000624, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::Temp_float_Variable_10' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_Subtract_FloatFloat_ReturnValue_8) == 0x000628, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_Subtract_FloatFloat_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, K2Node_Select_Default_8) == 0x00062C, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::K2Node_Select_Default_8' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, Temp_bool_Variable_9) == 0x000630, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::Temp_bool_Variable_9' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PlayAnimation_ReturnValue_18) == 0x000638, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PlayAnimation_ReturnValue_18' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, K2Node_Select_Default_9) == 0x000640, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::K2Node_Select_Default_9' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile, CallFunc_PlayAnimation_ReturnValue_19) == 0x000648, "Member 'ShowdownEventTile_C_ExecuteUbergraph_ShowdownEventTile::CallFunc_PlayAnimation_ReturnValue_19' has a wrong offset!");

// Function ShowdownEventTile.ShowdownEventTile_C.OnAddedToFocusPath
// 0x0008 (0x0008 - 0x0000)
struct ShowdownEventTile_C_OnAddedToFocusPath final
{
public:
	struct FFocusEvent                            InFocusEvent;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
};
static_assert(alignof(ShowdownEventTile_C_OnAddedToFocusPath) == 0x000004, "Wrong alignment on ShowdownEventTile_C_OnAddedToFocusPath");
static_assert(sizeof(ShowdownEventTile_C_OnAddedToFocusPath) == 0x000008, "Wrong size on ShowdownEventTile_C_OnAddedToFocusPath");
static_assert(offsetof(ShowdownEventTile_C_OnAddedToFocusPath, InFocusEvent) == 0x000000, "Member 'ShowdownEventTile_C_OnAddedToFocusPath::InFocusEvent' has a wrong offset!");

// Function ShowdownEventTile.ShowdownEventTile_C.OnRemovedFromFocusPath
// 0x0008 (0x0008 - 0x0000)
struct ShowdownEventTile_C_OnRemovedFromFocusPath final
{
public:
	struct FFocusEvent                            InFocusEvent;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
};
static_assert(alignof(ShowdownEventTile_C_OnRemovedFromFocusPath) == 0x000004, "Wrong alignment on ShowdownEventTile_C_OnRemovedFromFocusPath");
static_assert(sizeof(ShowdownEventTile_C_OnRemovedFromFocusPath) == 0x000008, "Wrong size on ShowdownEventTile_C_OnRemovedFromFocusPath");
static_assert(offsetof(ShowdownEventTile_C_OnRemovedFromFocusPath, InFocusEvent) == 0x000000, "Member 'ShowdownEventTile_C_OnRemovedFromFocusPath::InFocusEvent' has a wrong offset!");

// Function ShowdownEventTile.ShowdownEventTile_C.SetData
// 0x0020 (0x0020 - 0x0000)
struct ShowdownEventTile_C_SetData final
{
public:
	class FString                                 TournamentInfo;                                    // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 EventInfo;                                         // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(ShowdownEventTile_C_SetData) == 0x000008, "Wrong alignment on ShowdownEventTile_C_SetData");
static_assert(sizeof(ShowdownEventTile_C_SetData) == 0x000020, "Wrong size on ShowdownEventTile_C_SetData");
static_assert(offsetof(ShowdownEventTile_C_SetData, TournamentInfo) == 0x000000, "Member 'ShowdownEventTile_C_SetData::TournamentInfo' has a wrong offset!");
static_assert(offsetof(ShowdownEventTile_C_SetData, EventInfo) == 0x000010, "Member 'ShowdownEventTile_C_SetData::EventInfo' has a wrong offset!");

}

