#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ShowdownEventTileInfo

#include "Basic.hpp"

#include "ShowdownEventTileInfo_classes.hpp"
#include "ShowdownEventTileInfo_parameters.hpp"


namespace SDK
{

// Function ShowdownEventTileInfo.ShowdownEventTileInfo_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UShowdownEventTileInfo_C::Construct()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShowdownEventTileInfo.ShowdownEventTileInfo_C.EventAnimFocus
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    In                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UShowdownEventTileInfo_C::EventAnimFocus(bool In)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("EventAnimFocus");

	Params::ShowdownEventTileInfo_C_EventAnimFocus Parms{};

	Parms.In = In;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ShowdownEventTileInfo.ShowdownEventTileInfo_C.EventAnimHover
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    In                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UShowdownEventTileInfo_C::EventAnimHover(bool In)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("EventAnimHover");

	Params::ShowdownEventTileInfo_C_EventAnimHover Parms{};

	Parms.In = In;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ShowdownEventTileInfo.ShowdownEventTileInfo_C.EventColorize
// (BlueprintCallable, BlueprintEvent)

void UShowdownEventTileInfo_C::EventColorize()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("EventColorize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShowdownEventTileInfo.ShowdownEventTileInfo_C.EventStyleSocket
// (BlueprintCallable, BlueprintEvent)

void UShowdownEventTileInfo_C::EventStyleSocket()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("EventStyleSocket");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShowdownEventTileInfo.ShowdownEventTileInfo_C.ExecuteUbergraph_ShowdownEventTileInfo
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UShowdownEventTileInfo_C::ExecuteUbergraph_ShowdownEventTileInfo(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_ShowdownEventTileInfo");

	Params::ShowdownEventTileInfo_C_ExecuteUbergraph_ShowdownEventTileInfo Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ShowdownEventTileInfo.ShowdownEventTileInfo_C.RefreshDataBP
// (Event, Protected, BlueprintEvent)

void UShowdownEventTileInfo_C::RefreshDataBP()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("RefreshDataBP");

	UObject::ProcessEvent(Func, nullptr);
}

}

