#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SidebarProfileSubPanelIdentity

#include "Basic.hpp"

#include "SidebarProfileSubPanelIdentity_classes.hpp"
#include "SidebarProfileSubPanelIdentity_parameters.hpp"


namespace SDK
{

// Function SidebarProfileSubPanelIdentity.SidebarProfileSubPanelIdentity_C.ExecuteUbergraph_SidebarProfileSubPanelIdentity
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USidebarProfileSubPanelIdentity_C::ExecuteUbergraph_SidebarProfileSubPanelIdentity(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_SidebarProfileSubPanelIdentity");

	Params::SidebarProfileSubPanelIdentity_C_ExecuteUbergraph_SidebarProfileSubPanelIdentity Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SidebarProfileSubPanelIdentity.SidebarProfileSubPanelIdentity_C.OnFinishedProfileLoading
// (Event, Protected, BlueprintEvent)

void USidebarProfileSubPanelIdentity_C::OnFinishedProfileLoading()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnFinishedProfileLoading");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SidebarProfileSubPanelIdentity.SidebarProfileSubPanelIdentity_C.OnStartProfileLoading
// (Event, Protected, BlueprintEvent)

void USidebarProfileSubPanelIdentity_C::OnStartProfileLoading()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnStartProfileLoading");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SidebarProfileSubPanelIdentity.SidebarProfileSubPanelIdentity_C.SetBattlePassVisiblity
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bIsVisible                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USidebarProfileSubPanelIdentity_C::SetBattlePassVisiblity(bool bIsVisible)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetBattlePassVisiblity");

	Params::SidebarProfileSubPanelIdentity_C_SetBattlePassVisiblity Parms{};

	Parms.bIsVisible = bIsVisible;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SidebarProfileSubPanelIdentity.SidebarProfileSubPanelIdentity_C.SetFortniteCrewVisiblity
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bIsVisible                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USidebarProfileSubPanelIdentity_C::SetFortniteCrewVisiblity(bool bIsVisible)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetFortniteCrewVisiblity");

	Params::SidebarProfileSubPanelIdentity_C_SetFortniteCrewVisiblity Parms{};

	Parms.bIsVisible = bIsVisible;

	UObject::ProcessEvent(Func, &Parms);
}

}

