#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SrirachaRanchValet

#include "Basic.hpp"

#include "SrirachaRanchValet_classes.hpp"
#include "SrirachaRanchValet_parameters.hpp"


namespace SDK
{

// Function SrirachaRanchValet.StreamingRadioPlayerComponent_Valet.ValetVehicleExploded
// (Final, Native, Protected)
// Parameters:
// class AFortDagwoodVehicle*              Veh                                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UStreamingRadioPlayerComponent_Valet::ValetVehicleExploded(class AFortDagwoodVehicle* Veh)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ValetVehicleExploded");

	Params::StreamingRadioPlayerComponent_Valet_ValetVehicleExploded Parms{};

	Parms.Veh = Veh;

	UObject::ProcessEvent(Func, &Parms);
}

}

