#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SwimmingAnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "SwimmingAnimBP_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass SwimmingAnimBP.SwimmingAnimBP_C
// 0x6310 (0x6A90 - 0x0780)
class USwimmingAnimBP_C final : public UFortSwimmingLayerAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0780(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct SwimmingAnimBP::FAnimBlueprintGeneratedMutableData __AnimBlueprintMutables;                           // 0x0788(0x00B0)(HasGetValueTypeHash)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x0838(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x0840(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root_9;                              // 0x0848(0x0020)()
	struct FAnimNode_RotateRootBone               AnimGraphNode_RotateRootBone_1;                    // 0x0868(0x00A0)()
	struct FAnimNode_RotationOffsetBlendSpace     AnimGraphNode_RotationOffsetBlendSpace_3;          // 0x0908(0x01C0)()
	struct FAnimNode_RotationOffsetBlendSpace     AnimGraphNode_RotationOffsetBlendSpace_2;          // 0x0AC8(0x01C0)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_14;                  // 0x0C88(0x00C8)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_48;                 // 0x0D50(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_47;                 // 0x0D78(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_46;                 // 0x0DA0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_45;                 // 0x0DC8(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_14;                   // 0x0DF0(0x0040)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_23;                      // 0x0E30(0x0020)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_13;                   // 0x0E50(0x0040)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_22;                      // 0x0E90(0x0020)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_12;                   // 0x0EB0(0x0040)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_21;                      // 0x0EF0(0x0020)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_5;                      // 0x0F10(0x00B8)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_10;                   // 0x0FC8(0x0108)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_8;                   // 0x10D0(0x0088)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_15;                    // 0x1158(0x0028)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_4;                  // 0x1180(0x00E0)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_14;                    // 0x1260(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_11;                   // 0x1288(0x0040)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend_7;                       // 0x12C8(0x00C8)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_9;                    // 0x1390(0x0108)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_13;                    // 0x1498(0x0028)()
	struct FAnimNode_BlendListByEnum              AnimGraphNode_BlendListByEnum_2;                   // 0x14C0(0x0088)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_12;                    // 0x1548(0x0028)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive_1;                     // 0x1570(0x00C8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_10;                   // 0x1638(0x0040)()
	struct FAnimNode_Root                         AnimGraphNode_Root_8;                              // 0x1678(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_13;                  // 0x1698(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_7;                              // 0x1760(0x0020)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_44;                 // 0x1780(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_43;                 // 0x17A8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_42;                 // 0x17D0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_41;                 // 0x17F8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_40;                 // 0x1820(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_39;                 // 0x1848(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_38;                 // 0x1870(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_37;                 // 0x1898(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_36;                 // 0x18C0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_35;                 // 0x18E8(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_9;                    // 0x1910(0x0040)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_20;                      // 0x1950(0x0020)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_13;                 // 0x1970(0x0118)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_19;                      // 0x1A88(0x0020)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_12;                 // 0x1AA8(0x0118)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_18;                      // 0x1BC0(0x0020)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_8;                    // 0x1BE0(0x0040)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_17;                      // 0x1C20(0x0020)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_11;                    // 0x1C40(0x0028)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_16;                      // 0x1C68(0x0020)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_11;                 // 0x1C88(0x0118)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_15;                      // 0x1DA0(0x0020)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_4;                      // 0x1DC0(0x00B8)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_12;                  // 0x1E78(0x00C8)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_8;                    // 0x1F40(0x0108)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_11;                  // 0x2048(0x00C8)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_7;                   // 0x2110(0x0088)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_3;                  // 0x2198(0x00E0)()
	struct FAnimNode_RefPose                      AnimGraphNode_IdentityPose_2;                      // 0x2278(0x0010)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_10;                  // 0x2288(0x00C8)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_7;                    // 0x2350(0x0108)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_10;                    // 0x2458(0x0028)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_6;                    // 0x2480(0x0108)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_9;                     // 0x2588(0x0028)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_2;                  // 0x25B0(0x00E0)()
	struct FAnimNode_RefPose                      AnimGraphNode_IdentityPose_1;                      // 0x2690(0x0010)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_1;                  // 0x26A0(0x00E0)()
	struct FAnimNode_RefPose                      AnimGraphNode_IdentityPose;                        // 0x2780(0x0010)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive;                       // 0x2790(0x00C8)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_9;                   // 0x2858(0x00C8)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_5;                    // 0x2920(0x0108)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_8;                     // 0x2A28(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_34;                 // 0x2A50(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_33;                 // 0x2A78(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_32;                 // 0x2AA0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_31;                 // 0x2AC8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_30;                 // 0x2AF0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_29;                 // 0x2B18(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_28;                 // 0x2B40(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_27;                 // 0x2B68(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_26;                 // 0x2B90(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_25;                 // 0x2BB8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_24;                 // 0x2BE0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_23;                 // 0x2C08(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_22;                 // 0x2C30(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_21;                 // 0x2C58(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_20;                 // 0x2C80(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_19;                 // 0x2CA8(0x0028)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_5;             // 0x2CD0(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_6;                        // 0x2CF0(0x0108)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_5;             // 0x2DF8(0x0020)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_18;                 // 0x2E18(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_17;                 // 0x2E40(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_16;                 // 0x2E68(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_15;                 // 0x2E90(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_7;                    // 0x2EB8(0x0040)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_6;                   // 0x2EF8(0x0088)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_6;                    // 0x2F80(0x0040)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_14;                      // 0x2FC0(0x0020)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_10;                 // 0x2FE0(0x0118)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_13;                      // 0x30F8(0x0020)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_5;                    // 0x3118(0x0040)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_12;                      // 0x3158(0x0020)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_3;                      // 0x3178(0x00B8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_11;                      // 0x3230(0x0020)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_14;                 // 0x3250(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_4;                    // 0x3278(0x0040)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_10;                      // 0x32B8(0x0020)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_7;                     // 0x32D8(0x0028)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_9;                       // 0x3300(0x0020)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_6;                     // 0x3320(0x0028)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_8;                       // 0x3348(0x0020)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_2;                      // 0x3368(0x00B8)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_4;                    // 0x3420(0x0108)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_8;                   // 0x3528(0x00C8)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_3;                    // 0x35F0(0x0108)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend_6;                       // 0x36F8(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_6;                              // 0x37C0(0x0020)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_13;                 // 0x37E0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_12;                 // 0x3808(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_11;                 // 0x3830(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_10;                 // 0x3858(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_9;                  // 0x3880(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_8;                  // 0x38A8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_7;                  // 0x38D0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_6;                  // 0x38F8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_5;                  // 0x3920(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_4;                  // 0x3948(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_3;                    // 0x3970(0x0040)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_7;                       // 0x39B0(0x0020)()
	struct FAnimNode_RotationOffsetBlendSpace     AnimGraphNode_RotationOffsetBlendSpace_1;          // 0x39D0(0x01C0)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_4;             // 0x3B90(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_5;                        // 0x3BB0(0x0108)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_4;             // 0x3CB8(0x0020)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_9;                  // 0x3CD8(0x0118)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_6;                       // 0x3DF0(0x0020)()
	struct FAnimNode_RotationOffsetBlendSpace     AnimGraphNode_RotationOffsetBlendSpace;            // 0x3E10(0x01C0)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_3;             // 0x3FD0(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_4;                        // 0x3FF0(0x0108)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_3;             // 0x40F8(0x0020)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_8;                  // 0x4118(0x0118)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_5;                       // 0x4230(0x0020)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_2;                    // 0x4250(0x0040)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_4;                       // 0x4290(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_3;                        // 0x42B0(0x0108)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_2;             // 0x43B8(0x0020)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_2;             // 0x43D8(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_2;                        // 0x43F8(0x0108)()
	struct FAnimNode_ModifyCurve                  AnimGraphNode_ModifyCurve;                         // 0x4500(0x0100)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_5;                     // 0x4600(0x0028)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend_5;                       // 0x4628(0x00C8)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_4;                     // 0x46F0(0x0028)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_5;                   // 0x4718(0x0088)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_3;                     // 0x47A0(0x0028)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_4;                   // 0x47C8(0x0088)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_1;             // 0x4850(0x0020)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_1;             // 0x4870(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_1;                        // 0x4890(0x0108)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_2;                     // 0x4998(0x0028)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_3;                       // 0x49C0(0x0020)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_1;                      // 0x49E0(0x00B8)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_7;                   // 0x4A98(0x00C8)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_2;                    // 0x4B60(0x0108)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_6;                   // 0x4C68(0x00C8)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_1;                    // 0x4D30(0x0108)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_7;                  // 0x4E38(0x0118)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_3;                   // 0x4F50(0x0088)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_5;                   // 0x4FD8(0x00C8)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend_4;                       // 0x50A0(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_5;                              // 0x5168(0x0020)()
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator_1;                 // 0x5188(0x0040)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_4;                   // 0x51C8(0x00C8)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend_3;                       // 0x5290(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_4;                              // 0x5358(0x0020)()
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator;                   // 0x5378(0x0040)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_3;                   // 0x53B8(0x00C8)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend_2;                       // 0x5480(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_3;                              // 0x5548(0x0020)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_6;                  // 0x5568(0x0118)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_5;                  // 0x5680(0x0118)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_2;                   // 0x5798(0x0088)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_2;                   // 0x5820(0x00C8)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend_1;                       // 0x58E8(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_2;                              // 0x59B0(0x0020)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_3;                  // 0x59D0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_2;                  // 0x59F8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_1;                  // 0x5A20(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult;                    // 0x5A48(0x0028)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_4;                  // 0x5A70(0x0118)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_2;                       // 0x5B88(0x0020)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_3;                  // 0x5BA8(0x0118)()
	struct FAnimNode_BlendListByEnum              AnimGraphNode_BlendListByEnum_1;                   // 0x5CC0(0x0088)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_2;                  // 0x5D48(0x0118)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_1;                       // 0x5E60(0x0020)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_1;                  // 0x5E80(0x0118)()
	struct FAnimNode_BlendListByEnum              AnimGraphNode_BlendListByEnum;                     // 0x5F98(0x0088)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer;                    // 0x6020(0x0118)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult;                         // 0x6138(0x0020)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine;                        // 0x6158(0x00B8)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x6210(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone;                          // 0x6230(0x0108)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x6338(0x0020)()
	struct FAnimNode_RotateRootBone               AnimGraphNode_RotateRootBone;                      // 0x6358(0x00A0)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_1;                   // 0x63F8(0x00C8)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose;                      // 0x64C0(0x0108)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend;                    // 0x65C8(0x00E0)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_1;                     // 0x66A8(0x0028)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_1;                   // 0x66D0(0x0088)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose;                       // 0x6758(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1;                    // 0x6780(0x0040)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend;                         // 0x67C0(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_1;                              // 0x6888(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose;                     // 0x68A8(0x00C8)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool;                     // 0x6970(0x0088)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x69F8(0x0040)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x6A38(0x0020)()
	EFortPlayerAnimBodyType                       AnimBodyTypePassThrough;                           // 0x6A58(0x0001)(BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6A59[0x3];                                     // 0x6A59(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         MainInstanceDiveJumpLayerAlpha;                    // 0x6A5C(0x0004)(BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsHidingInPropLayer2;                              // 0x6A60(0x0001)(BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6A61[0x3];                                     // 0x6A61(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         MainInstanceAdditiveLayerAlpha;                    // 0x6A64(0x0004)(BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         LocomotionAdditiveAlphaLayer;                      // 0x6A68(0x0004)(BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         DisableIKRootAdditiveCurveAlphaLayer;              // 0x6A6C(0x0004)(BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         DisableArmsHeadAdditiveCurveAlphaLayer;            // 0x6A70(0x0004)(BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         PlayMeleeAttackAOLayer;                            // 0x6A74(0x0004)(BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsHidingInPropLayer;                               // 0x6A78(0x0001)(BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          AllowSprintStop;                                   // 0x6A79(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ChangeMovementToVelocityFromAccel;                 // 0x6A7A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6A7B[0x1];                                     // 0x6A7B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         LocalAccelYawAngleAtStart;                         // 0x6A7C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         PivotAngle;                                        // 0x6A80(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFortWeaponCoreAnimation                      WeaponCoreAnim;                                    // 0x6A84(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void AnimNotify_SwimMovementAccelAdditive_Exited_Layer();
	void AnimNotify_SwimSprint_Entered_Layer();
	void AnimNotify_SwimSprintSlow_Entered_Layer();
	void AnimNotify_SwimSprintStart_Entered_Layer();
	void AnimNotify_SwimSprintStart_Exited_Layer();
	void AnimNotify_SwimStartAdditive_Entered_Layer();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_SwimmingAnimBP_AnimGraphNode_TransitionResult_5830B69443C9B79B5F980CAE5DEC8E36();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_SwimmingAnimBP_AnimGraphNode_TransitionResult_E6B49F01423E469AF176989D25F6BA2A();
	void ExecuteUbergraph_SwimmingAnimBP(int32 EntryPoint);
	void SwimmingAdditiveLayer(const struct FPoseLink& IdleAdditive_Cache, const struct FPoseLink& MovementAdditiveLayerPose_Cache, const struct FPoseLink& FullBody, float PlayMeleeAttackAOLayer_0, float DisableArmsHeadAdditiveCurveAlphaLayer_0, float DisableIKRootAdditiveCurveAlphaLayer_0, float LocomotionAdditiveAlphaLayer_0, float MainInstanceAdditiveLayerAlpha_0, const struct FPoseLink& UpperAndLowerBody_Cache, const struct FPoseLink& SprintingPose_PostMask_Cache, struct FPoseLink* SwimmingAdditiveLayer_0);
	void SwimmingDiveJumpingLayer(const struct FPoseLink& PassThroughSwimmingDiveJumping, bool IsHidingInPropLayer2_0, float MainInstanceDiveJumpLayerAlpha_0, EFortPlayerAnimBodyType AnimBodyTypePassThrough_0, struct FPoseLink* SwimmingDiveJumpingLayer_0);
	void SwimmingFullBodyAdditiveLayer(const struct FPoseLink& PassThroughFullBodyAdditive, struct FPoseLink* SwimmingFullBodyAdditiveLayer_0);
	void SwimmingLayer(const struct FPoseLink& MainPlayerAnimBP, struct FPoseLink* SwimmingLayer_0);
	void SwimmingLowerBodyLayer(const struct FPoseLink& UpperBody_Cache, const struct FPoseLink& PreUpperBodySlot_Cache, const struct FPoseLink& PassThroughSwimmingLowerBody, struct FPoseLink* SwimmingLowerBodyLayer_0);
	void SwimmingMovementAdditiveLayerPose(const struct FPoseLink& PassThroughSwimmingMovementAdditive, struct FPoseLink* SwimmingMovementAdditiveLayerPose_0);
	void SwimmingSprintLayer(const struct FPoseLink& PassThroughSwimmingSprint, bool IsHidingInPropLayer_0, struct FPoseLink* SwimmingSprintLayer_0);
	void SwimmingUpperBodyPoseNonTargetingLayer(const struct FPoseLink& PassThroughSwimmingUpperBodyPoseNonTargeting, struct FPoseLink* SwimmingUpperBodyPoseNonTargetingLayer_0);
	void SwimmingUpperBodyPoseTargetingLayer(const struct FPoseLink& PassThroughSwimmingUpperBodyPoseTargeting, struct FPoseLink* SwimmingUpperBodyPoseTargetingLayer_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SwimmingAnimBP_C">();
	}
	static class USwimmingAnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USwimmingAnimBP_C>();
	}
};
static_assert(alignof(USwimmingAnimBP_C) == 0x000010, "Wrong alignment on USwimmingAnimBP_C");
static_assert(sizeof(USwimmingAnimBP_C) == 0x006A90, "Wrong size on USwimmingAnimBP_C");
static_assert(offsetof(USwimmingAnimBP_C, UberGraphFrame) == 0x000780, "Member 'USwimmingAnimBP_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, __AnimBlueprintMutables) == 0x000788, "Member 'USwimmingAnimBP_C::__AnimBlueprintMutables' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimBlueprintExtension_PropertyAccess) == 0x000838, "Member 'USwimmingAnimBP_C::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimBlueprintExtension_Base) == 0x000840, "Member 'USwimmingAnimBP_C::AnimBlueprintExtension_Base' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_Root_9) == 0x000848, "Member 'USwimmingAnimBP_C::AnimGraphNode_Root_9' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_RotateRootBone_1) == 0x000868, "Member 'USwimmingAnimBP_C::AnimGraphNode_RotateRootBone_1' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_RotationOffsetBlendSpace_3) == 0x000908, "Member 'USwimmingAnimBP_C::AnimGraphNode_RotationOffsetBlendSpace_3' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_RotationOffsetBlendSpace_2) == 0x000AC8, "Member 'USwimmingAnimBP_C::AnimGraphNode_RotationOffsetBlendSpace_2' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_LinkedInputPose_14) == 0x000C88, "Member 'USwimmingAnimBP_C::AnimGraphNode_LinkedInputPose_14' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_48) == 0x000D50, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_48' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_47) == 0x000D78, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_47' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_46) == 0x000DA0, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_46' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_45) == 0x000DC8, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_45' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_SequencePlayer_14) == 0x000DF0, "Member 'USwimmingAnimBP_C::AnimGraphNode_SequencePlayer_14' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateResult_23) == 0x000E30, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateResult_23' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_SequencePlayer_13) == 0x000E50, "Member 'USwimmingAnimBP_C::AnimGraphNode_SequencePlayer_13' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateResult_22) == 0x000E90, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateResult_22' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_SequencePlayer_12) == 0x000EB0, "Member 'USwimmingAnimBP_C::AnimGraphNode_SequencePlayer_12' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateResult_21) == 0x000EF0, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateResult_21' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateMachine_5) == 0x000F10, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateMachine_5' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_SaveCachedPose_10) == 0x000FC8, "Member 'USwimmingAnimBP_C::AnimGraphNode_SaveCachedPose_10' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_BlendListByBool_8) == 0x0010D0, "Member 'USwimmingAnimBP_C::AnimGraphNode_BlendListByBool_8' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_UseCachedPose_15) == 0x001158, "Member 'USwimmingAnimBP_C::AnimGraphNode_UseCachedPose_15' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_LayeredBoneBlend_4) == 0x001180, "Member 'USwimmingAnimBP_C::AnimGraphNode_LayeredBoneBlend_4' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_UseCachedPose_14) == 0x001260, "Member 'USwimmingAnimBP_C::AnimGraphNode_UseCachedPose_14' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_SequencePlayer_11) == 0x001288, "Member 'USwimmingAnimBP_C::AnimGraphNode_SequencePlayer_11' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TwoWayBlend_7) == 0x0012C8, "Member 'USwimmingAnimBP_C::AnimGraphNode_TwoWayBlend_7' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_SaveCachedPose_9) == 0x001390, "Member 'USwimmingAnimBP_C::AnimGraphNode_SaveCachedPose_9' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_UseCachedPose_13) == 0x001498, "Member 'USwimmingAnimBP_C::AnimGraphNode_UseCachedPose_13' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_BlendListByEnum_2) == 0x0014C0, "Member 'USwimmingAnimBP_C::AnimGraphNode_BlendListByEnum_2' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_UseCachedPose_12) == 0x001548, "Member 'USwimmingAnimBP_C::AnimGraphNode_UseCachedPose_12' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_ApplyAdditive_1) == 0x001570, "Member 'USwimmingAnimBP_C::AnimGraphNode_ApplyAdditive_1' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_SequencePlayer_10) == 0x001638, "Member 'USwimmingAnimBP_C::AnimGraphNode_SequencePlayer_10' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_Root_8) == 0x001678, "Member 'USwimmingAnimBP_C::AnimGraphNode_Root_8' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_LinkedInputPose_13) == 0x001698, "Member 'USwimmingAnimBP_C::AnimGraphNode_LinkedInputPose_13' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_Root_7) == 0x001760, "Member 'USwimmingAnimBP_C::AnimGraphNode_Root_7' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_44) == 0x001780, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_44' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_43) == 0x0017A8, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_43' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_42) == 0x0017D0, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_42' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_41) == 0x0017F8, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_41' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_40) == 0x001820, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_40' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_39) == 0x001848, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_39' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_38) == 0x001870, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_38' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_37) == 0x001898, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_37' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_36) == 0x0018C0, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_36' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_35) == 0x0018E8, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_35' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_SequencePlayer_9) == 0x001910, "Member 'USwimmingAnimBP_C::AnimGraphNode_SequencePlayer_9' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateResult_20) == 0x001950, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateResult_20' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_BlendSpacePlayer_13) == 0x001970, "Member 'USwimmingAnimBP_C::AnimGraphNode_BlendSpacePlayer_13' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateResult_19) == 0x001A88, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateResult_19' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_BlendSpacePlayer_12) == 0x001AA8, "Member 'USwimmingAnimBP_C::AnimGraphNode_BlendSpacePlayer_12' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateResult_18) == 0x001BC0, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateResult_18' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_SequencePlayer_8) == 0x001BE0, "Member 'USwimmingAnimBP_C::AnimGraphNode_SequencePlayer_8' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateResult_17) == 0x001C20, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateResult_17' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_UseCachedPose_11) == 0x001C40, "Member 'USwimmingAnimBP_C::AnimGraphNode_UseCachedPose_11' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateResult_16) == 0x001C68, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateResult_16' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_BlendSpacePlayer_11) == 0x001C88, "Member 'USwimmingAnimBP_C::AnimGraphNode_BlendSpacePlayer_11' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateResult_15) == 0x001DA0, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateResult_15' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateMachine_4) == 0x001DC0, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateMachine_4' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_LinkedInputPose_12) == 0x001E78, "Member 'USwimmingAnimBP_C::AnimGraphNode_LinkedInputPose_12' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_SaveCachedPose_8) == 0x001F40, "Member 'USwimmingAnimBP_C::AnimGraphNode_SaveCachedPose_8' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_LinkedInputPose_11) == 0x002048, "Member 'USwimmingAnimBP_C::AnimGraphNode_LinkedInputPose_11' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_BlendListByBool_7) == 0x002110, "Member 'USwimmingAnimBP_C::AnimGraphNode_BlendListByBool_7' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_LayeredBoneBlend_3) == 0x002198, "Member 'USwimmingAnimBP_C::AnimGraphNode_LayeredBoneBlend_3' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_IdentityPose_2) == 0x002278, "Member 'USwimmingAnimBP_C::AnimGraphNode_IdentityPose_2' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_LinkedInputPose_10) == 0x002288, "Member 'USwimmingAnimBP_C::AnimGraphNode_LinkedInputPose_10' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_SaveCachedPose_7) == 0x002350, "Member 'USwimmingAnimBP_C::AnimGraphNode_SaveCachedPose_7' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_UseCachedPose_10) == 0x002458, "Member 'USwimmingAnimBP_C::AnimGraphNode_UseCachedPose_10' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_SaveCachedPose_6) == 0x002480, "Member 'USwimmingAnimBP_C::AnimGraphNode_SaveCachedPose_6' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_UseCachedPose_9) == 0x002588, "Member 'USwimmingAnimBP_C::AnimGraphNode_UseCachedPose_9' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_LayeredBoneBlend_2) == 0x0025B0, "Member 'USwimmingAnimBP_C::AnimGraphNode_LayeredBoneBlend_2' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_IdentityPose_1) == 0x002690, "Member 'USwimmingAnimBP_C::AnimGraphNode_IdentityPose_1' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_LayeredBoneBlend_1) == 0x0026A0, "Member 'USwimmingAnimBP_C::AnimGraphNode_LayeredBoneBlend_1' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_IdentityPose) == 0x002780, "Member 'USwimmingAnimBP_C::AnimGraphNode_IdentityPose' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_ApplyAdditive) == 0x002790, "Member 'USwimmingAnimBP_C::AnimGraphNode_ApplyAdditive' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_LinkedInputPose_9) == 0x002858, "Member 'USwimmingAnimBP_C::AnimGraphNode_LinkedInputPose_9' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_SaveCachedPose_5) == 0x002920, "Member 'USwimmingAnimBP_C::AnimGraphNode_SaveCachedPose_5' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_UseCachedPose_8) == 0x002A28, "Member 'USwimmingAnimBP_C::AnimGraphNode_UseCachedPose_8' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_34) == 0x002A50, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_34' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_33) == 0x002A78, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_33' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_32) == 0x002AA0, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_32' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_31) == 0x002AC8, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_31' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_30) == 0x002AF0, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_30' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_29) == 0x002B18, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_29' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_28) == 0x002B40, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_28' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_27) == 0x002B68, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_27' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_26) == 0x002B90, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_26' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_25) == 0x002BB8, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_25' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_24) == 0x002BE0, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_24' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_23) == 0x002C08, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_23' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_22) == 0x002C30, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_22' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_21) == 0x002C58, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_21' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_20) == 0x002C80, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_20' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_19) == 0x002CA8, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_19' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_ComponentToLocalSpace_5) == 0x002CD0, "Member 'USwimmingAnimBP_C::AnimGraphNode_ComponentToLocalSpace_5' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_ModifyBone_6) == 0x002CF0, "Member 'USwimmingAnimBP_C::AnimGraphNode_ModifyBone_6' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_LocalToComponentSpace_5) == 0x002DF8, "Member 'USwimmingAnimBP_C::AnimGraphNode_LocalToComponentSpace_5' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_18) == 0x002E18, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_18' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_17) == 0x002E40, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_17' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_16) == 0x002E68, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_16' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_15) == 0x002E90, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_15' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_SequencePlayer_7) == 0x002EB8, "Member 'USwimmingAnimBP_C::AnimGraphNode_SequencePlayer_7' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_BlendListByBool_6) == 0x002EF8, "Member 'USwimmingAnimBP_C::AnimGraphNode_BlendListByBool_6' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_SequencePlayer_6) == 0x002F80, "Member 'USwimmingAnimBP_C::AnimGraphNode_SequencePlayer_6' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateResult_14) == 0x002FC0, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateResult_14' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_BlendSpacePlayer_10) == 0x002FE0, "Member 'USwimmingAnimBP_C::AnimGraphNode_BlendSpacePlayer_10' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateResult_13) == 0x0030F8, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateResult_13' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_SequencePlayer_5) == 0x003118, "Member 'USwimmingAnimBP_C::AnimGraphNode_SequencePlayer_5' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateResult_12) == 0x003158, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateResult_12' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateMachine_3) == 0x003178, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateMachine_3' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateResult_11) == 0x003230, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateResult_11' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_14) == 0x003250, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_14' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_SequencePlayer_4) == 0x003278, "Member 'USwimmingAnimBP_C::AnimGraphNode_SequencePlayer_4' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateResult_10) == 0x0032B8, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateResult_10' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_UseCachedPose_7) == 0x0032D8, "Member 'USwimmingAnimBP_C::AnimGraphNode_UseCachedPose_7' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateResult_9) == 0x003300, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateResult_9' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_UseCachedPose_6) == 0x003320, "Member 'USwimmingAnimBP_C::AnimGraphNode_UseCachedPose_6' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateResult_8) == 0x003348, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateResult_8' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateMachine_2) == 0x003368, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateMachine_2' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_SaveCachedPose_4) == 0x003420, "Member 'USwimmingAnimBP_C::AnimGraphNode_SaveCachedPose_4' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_LinkedInputPose_8) == 0x003528, "Member 'USwimmingAnimBP_C::AnimGraphNode_LinkedInputPose_8' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_SaveCachedPose_3) == 0x0035F0, "Member 'USwimmingAnimBP_C::AnimGraphNode_SaveCachedPose_3' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TwoWayBlend_6) == 0x0036F8, "Member 'USwimmingAnimBP_C::AnimGraphNode_TwoWayBlend_6' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_Root_6) == 0x0037C0, "Member 'USwimmingAnimBP_C::AnimGraphNode_Root_6' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_13) == 0x0037E0, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_13' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_12) == 0x003808, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_12' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_11) == 0x003830, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_11' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_10) == 0x003858, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_10' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_9) == 0x003880, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_9' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_8) == 0x0038A8, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_8' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_7) == 0x0038D0, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_7' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_6) == 0x0038F8, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_6' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_5) == 0x003920, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_5' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_4) == 0x003948, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_4' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_SequencePlayer_3) == 0x003970, "Member 'USwimmingAnimBP_C::AnimGraphNode_SequencePlayer_3' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateResult_7) == 0x0039B0, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateResult_7' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_RotationOffsetBlendSpace_1) == 0x0039D0, "Member 'USwimmingAnimBP_C::AnimGraphNode_RotationOffsetBlendSpace_1' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_ComponentToLocalSpace_4) == 0x003B90, "Member 'USwimmingAnimBP_C::AnimGraphNode_ComponentToLocalSpace_4' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_ModifyBone_5) == 0x003BB0, "Member 'USwimmingAnimBP_C::AnimGraphNode_ModifyBone_5' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_LocalToComponentSpace_4) == 0x003CB8, "Member 'USwimmingAnimBP_C::AnimGraphNode_LocalToComponentSpace_4' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_BlendSpacePlayer_9) == 0x003CD8, "Member 'USwimmingAnimBP_C::AnimGraphNode_BlendSpacePlayer_9' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateResult_6) == 0x003DF0, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateResult_6' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_RotationOffsetBlendSpace) == 0x003E10, "Member 'USwimmingAnimBP_C::AnimGraphNode_RotationOffsetBlendSpace' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_ComponentToLocalSpace_3) == 0x003FD0, "Member 'USwimmingAnimBP_C::AnimGraphNode_ComponentToLocalSpace_3' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_ModifyBone_4) == 0x003FF0, "Member 'USwimmingAnimBP_C::AnimGraphNode_ModifyBone_4' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_LocalToComponentSpace_3) == 0x0040F8, "Member 'USwimmingAnimBP_C::AnimGraphNode_LocalToComponentSpace_3' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_BlendSpacePlayer_8) == 0x004118, "Member 'USwimmingAnimBP_C::AnimGraphNode_BlendSpacePlayer_8' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateResult_5) == 0x004230, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateResult_5' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_SequencePlayer_2) == 0x004250, "Member 'USwimmingAnimBP_C::AnimGraphNode_SequencePlayer_2' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateResult_4) == 0x004290, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateResult_4' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_ModifyBone_3) == 0x0042B0, "Member 'USwimmingAnimBP_C::AnimGraphNode_ModifyBone_3' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_ComponentToLocalSpace_2) == 0x0043B8, "Member 'USwimmingAnimBP_C::AnimGraphNode_ComponentToLocalSpace_2' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_LocalToComponentSpace_2) == 0x0043D8, "Member 'USwimmingAnimBP_C::AnimGraphNode_LocalToComponentSpace_2' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_ModifyBone_2) == 0x0043F8, "Member 'USwimmingAnimBP_C::AnimGraphNode_ModifyBone_2' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_ModifyCurve) == 0x004500, "Member 'USwimmingAnimBP_C::AnimGraphNode_ModifyCurve' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_UseCachedPose_5) == 0x004600, "Member 'USwimmingAnimBP_C::AnimGraphNode_UseCachedPose_5' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TwoWayBlend_5) == 0x004628, "Member 'USwimmingAnimBP_C::AnimGraphNode_TwoWayBlend_5' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_UseCachedPose_4) == 0x0046F0, "Member 'USwimmingAnimBP_C::AnimGraphNode_UseCachedPose_4' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_BlendListByBool_5) == 0x004718, "Member 'USwimmingAnimBP_C::AnimGraphNode_BlendListByBool_5' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_UseCachedPose_3) == 0x0047A0, "Member 'USwimmingAnimBP_C::AnimGraphNode_UseCachedPose_3' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_BlendListByBool_4) == 0x0047C8, "Member 'USwimmingAnimBP_C::AnimGraphNode_BlendListByBool_4' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_LocalToComponentSpace_1) == 0x004850, "Member 'USwimmingAnimBP_C::AnimGraphNode_LocalToComponentSpace_1' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_ComponentToLocalSpace_1) == 0x004870, "Member 'USwimmingAnimBP_C::AnimGraphNode_ComponentToLocalSpace_1' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_ModifyBone_1) == 0x004890, "Member 'USwimmingAnimBP_C::AnimGraphNode_ModifyBone_1' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_UseCachedPose_2) == 0x004998, "Member 'USwimmingAnimBP_C::AnimGraphNode_UseCachedPose_2' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateResult_3) == 0x0049C0, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateResult_3' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateMachine_1) == 0x0049E0, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateMachine_1' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_LinkedInputPose_7) == 0x004A98, "Member 'USwimmingAnimBP_C::AnimGraphNode_LinkedInputPose_7' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_SaveCachedPose_2) == 0x004B60, "Member 'USwimmingAnimBP_C::AnimGraphNode_SaveCachedPose_2' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_LinkedInputPose_6) == 0x004C68, "Member 'USwimmingAnimBP_C::AnimGraphNode_LinkedInputPose_6' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_SaveCachedPose_1) == 0x004D30, "Member 'USwimmingAnimBP_C::AnimGraphNode_SaveCachedPose_1' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_BlendSpacePlayer_7) == 0x004E38, "Member 'USwimmingAnimBP_C::AnimGraphNode_BlendSpacePlayer_7' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_BlendListByBool_3) == 0x004F50, "Member 'USwimmingAnimBP_C::AnimGraphNode_BlendListByBool_3' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_LinkedInputPose_5) == 0x004FD8, "Member 'USwimmingAnimBP_C::AnimGraphNode_LinkedInputPose_5' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TwoWayBlend_4) == 0x0050A0, "Member 'USwimmingAnimBP_C::AnimGraphNode_TwoWayBlend_4' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_Root_5) == 0x005168, "Member 'USwimmingAnimBP_C::AnimGraphNode_Root_5' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_SequenceEvaluator_1) == 0x005188, "Member 'USwimmingAnimBP_C::AnimGraphNode_SequenceEvaluator_1' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_LinkedInputPose_4) == 0x0051C8, "Member 'USwimmingAnimBP_C::AnimGraphNode_LinkedInputPose_4' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TwoWayBlend_3) == 0x005290, "Member 'USwimmingAnimBP_C::AnimGraphNode_TwoWayBlend_3' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_Root_4) == 0x005358, "Member 'USwimmingAnimBP_C::AnimGraphNode_Root_4' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_SequenceEvaluator) == 0x005378, "Member 'USwimmingAnimBP_C::AnimGraphNode_SequenceEvaluator' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_LinkedInputPose_3) == 0x0053B8, "Member 'USwimmingAnimBP_C::AnimGraphNode_LinkedInputPose_3' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TwoWayBlend_2) == 0x005480, "Member 'USwimmingAnimBP_C::AnimGraphNode_TwoWayBlend_2' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_Root_3) == 0x005548, "Member 'USwimmingAnimBP_C::AnimGraphNode_Root_3' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_BlendSpacePlayer_6) == 0x005568, "Member 'USwimmingAnimBP_C::AnimGraphNode_BlendSpacePlayer_6' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_BlendSpacePlayer_5) == 0x005680, "Member 'USwimmingAnimBP_C::AnimGraphNode_BlendSpacePlayer_5' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_BlendListByBool_2) == 0x005798, "Member 'USwimmingAnimBP_C::AnimGraphNode_BlendListByBool_2' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_LinkedInputPose_2) == 0x005820, "Member 'USwimmingAnimBP_C::AnimGraphNode_LinkedInputPose_2' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TwoWayBlend_1) == 0x0058E8, "Member 'USwimmingAnimBP_C::AnimGraphNode_TwoWayBlend_1' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_Root_2) == 0x0059B0, "Member 'USwimmingAnimBP_C::AnimGraphNode_Root_2' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_3) == 0x0059D0, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_3' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_2) == 0x0059F8, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_2' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult_1) == 0x005A20, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult_1' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TransitionResult) == 0x005A48, "Member 'USwimmingAnimBP_C::AnimGraphNode_TransitionResult' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_BlendSpacePlayer_4) == 0x005A70, "Member 'USwimmingAnimBP_C::AnimGraphNode_BlendSpacePlayer_4' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateResult_2) == 0x005B88, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateResult_2' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_BlendSpacePlayer_3) == 0x005BA8, "Member 'USwimmingAnimBP_C::AnimGraphNode_BlendSpacePlayer_3' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_BlendListByEnum_1) == 0x005CC0, "Member 'USwimmingAnimBP_C::AnimGraphNode_BlendListByEnum_1' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_BlendSpacePlayer_2) == 0x005D48, "Member 'USwimmingAnimBP_C::AnimGraphNode_BlendSpacePlayer_2' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateResult_1) == 0x005E60, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateResult_1' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_BlendSpacePlayer_1) == 0x005E80, "Member 'USwimmingAnimBP_C::AnimGraphNode_BlendSpacePlayer_1' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_BlendListByEnum) == 0x005F98, "Member 'USwimmingAnimBP_C::AnimGraphNode_BlendListByEnum' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_BlendSpacePlayer) == 0x006020, "Member 'USwimmingAnimBP_C::AnimGraphNode_BlendSpacePlayer' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateResult) == 0x006138, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateResult' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_StateMachine) == 0x006158, "Member 'USwimmingAnimBP_C::AnimGraphNode_StateMachine' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_LocalToComponentSpace) == 0x006210, "Member 'USwimmingAnimBP_C::AnimGraphNode_LocalToComponentSpace' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_ModifyBone) == 0x006230, "Member 'USwimmingAnimBP_C::AnimGraphNode_ModifyBone' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_ComponentToLocalSpace) == 0x006338, "Member 'USwimmingAnimBP_C::AnimGraphNode_ComponentToLocalSpace' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_RotateRootBone) == 0x006358, "Member 'USwimmingAnimBP_C::AnimGraphNode_RotateRootBone' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_LinkedInputPose_1) == 0x0063F8, "Member 'USwimmingAnimBP_C::AnimGraphNode_LinkedInputPose_1' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_SaveCachedPose) == 0x0064C0, "Member 'USwimmingAnimBP_C::AnimGraphNode_SaveCachedPose' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_LayeredBoneBlend) == 0x0065C8, "Member 'USwimmingAnimBP_C::AnimGraphNode_LayeredBoneBlend' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_UseCachedPose_1) == 0x0066A8, "Member 'USwimmingAnimBP_C::AnimGraphNode_UseCachedPose_1' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_BlendListByBool_1) == 0x0066D0, "Member 'USwimmingAnimBP_C::AnimGraphNode_BlendListByBool_1' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_UseCachedPose) == 0x006758, "Member 'USwimmingAnimBP_C::AnimGraphNode_UseCachedPose' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_SequencePlayer_1) == 0x006780, "Member 'USwimmingAnimBP_C::AnimGraphNode_SequencePlayer_1' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_TwoWayBlend) == 0x0067C0, "Member 'USwimmingAnimBP_C::AnimGraphNode_TwoWayBlend' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_Root_1) == 0x006888, "Member 'USwimmingAnimBP_C::AnimGraphNode_Root_1' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_LinkedInputPose) == 0x0068A8, "Member 'USwimmingAnimBP_C::AnimGraphNode_LinkedInputPose' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_BlendListByBool) == 0x006970, "Member 'USwimmingAnimBP_C::AnimGraphNode_BlendListByBool' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_SequencePlayer) == 0x0069F8, "Member 'USwimmingAnimBP_C::AnimGraphNode_SequencePlayer' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimGraphNode_Root) == 0x006A38, "Member 'USwimmingAnimBP_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AnimBodyTypePassThrough) == 0x006A58, "Member 'USwimmingAnimBP_C::AnimBodyTypePassThrough' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, MainInstanceDiveJumpLayerAlpha) == 0x006A5C, "Member 'USwimmingAnimBP_C::MainInstanceDiveJumpLayerAlpha' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, IsHidingInPropLayer2) == 0x006A60, "Member 'USwimmingAnimBP_C::IsHidingInPropLayer2' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, MainInstanceAdditiveLayerAlpha) == 0x006A64, "Member 'USwimmingAnimBP_C::MainInstanceAdditiveLayerAlpha' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, LocomotionAdditiveAlphaLayer) == 0x006A68, "Member 'USwimmingAnimBP_C::LocomotionAdditiveAlphaLayer' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, DisableIKRootAdditiveCurveAlphaLayer) == 0x006A6C, "Member 'USwimmingAnimBP_C::DisableIKRootAdditiveCurveAlphaLayer' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, DisableArmsHeadAdditiveCurveAlphaLayer) == 0x006A70, "Member 'USwimmingAnimBP_C::DisableArmsHeadAdditiveCurveAlphaLayer' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, PlayMeleeAttackAOLayer) == 0x006A74, "Member 'USwimmingAnimBP_C::PlayMeleeAttackAOLayer' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, IsHidingInPropLayer) == 0x006A78, "Member 'USwimmingAnimBP_C::IsHidingInPropLayer' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, AllowSprintStop) == 0x006A79, "Member 'USwimmingAnimBP_C::AllowSprintStop' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, ChangeMovementToVelocityFromAccel) == 0x006A7A, "Member 'USwimmingAnimBP_C::ChangeMovementToVelocityFromAccel' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, LocalAccelYawAngleAtStart) == 0x006A7C, "Member 'USwimmingAnimBP_C::LocalAccelYawAngleAtStart' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, PivotAngle) == 0x006A80, "Member 'USwimmingAnimBP_C::PivotAngle' has a wrong offset!");
static_assert(offsetof(USwimmingAnimBP_C, WeaponCoreAnim) == 0x006A84, "Member 'USwimmingAnimBP_C::WeaponCoreAnim' has a wrong offset!");

}

